# Generated by Django 5.1.1 on 2024-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0002_userprofile_challenge_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ideas_created',
            field=models.IntegerField(default=0),
        ),
    ]
