# Generated by Django 5.1.1 on 2024-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0003_userprofile_ideas_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
