# Generated by Django 5.1.1 on 2024-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0007_alter_challenge_challenge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
