# Generated by Django 5.1.1 on 2024-09-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0007_remove_challenge_challenge_id_alter_challenge_id_and_more'),
        ('roche_app', '0008_challenge_end_date'),
    ]

    operations = [
    ]
